// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtDGjOCzqdfFzyZfQJLtAoEz2H1IPF_HE',
    appId: '1:1000548465532:web:07a15973c441c48752c2f9',
    messagingSenderId: '1000548465532',
    projectId: 'firebasewhatsapp',
    authDomain: 'fir-whatsapp-9f173.firebaseapp.com',
    storageBucket: 'firebasewhatsapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaa_Ac2YLvhy06nuE_uojD-prHM8LuqmE',
    appId: '1:1000548465532:android:5cc20a93d161ca5c52c2f9',
    messagingSenderId: '1000548465532',
    projectId: 'firebasewhatsapp',
    storageBucket: 'firebasewhatsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtRIVkommDoZfodzJ1nhbHcZ0Ysf2VRrE',
    appId: '1:1000548465532:ios:b74edcc92a6465bb52c2f9',
    messagingSenderId: '1000548465532',
    projectId: 'firebasewhatsapp',
    storageBucket: 'firebasewhatsapp.appspot.com',
    iosClientId: '1000548465532-gh5l85prn52p7dm69pa7guqiqip9ev6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
